### ISSUE TITLE
Was the interface left out?

### ISSUE THREAD

**Issue by EddieOne** [playtomic/gameapi-as3#1]
Hi,

Great software, I wish I knew about it when it was still active. I'm working on creating some of the same features. I'm wondering though, the interface is not included right? Also, some features were left out like heat tracking and level tracking?

Best regards

**Comment by benlowry** [comment]
Yeah there's no website for it anymore, it's not been a priority because on a single-user basis a web interface is only slighter better than just diving into your database through the vendor's dashboards.  

The heat maps and analytics didn't make the transition to open source, that stuff was not very portable or supportable + it was all .NET + MSSQL which meant significantly higher setup requirements.

**Comment by EddieOne** [comment]
Thanks for the reply Ben. I'm probably going to use Playtomic as a starting point and continuing your work. I have spent a few hours in the server code and tried tests in html5 and as3. If there was one thing I could change to make the project more successful, what would it be?

**Comment by benlowry** [comment]
I definitely think people prefer hosted services over self-hosted, even as simple as heroku makes it there is a lot of resistance because of the added responsibility in areas where most game developers don’t have any experience.

If you want to compete with GameCenter, GameCircle, Google Play Services etc you have to either saves developers’  time, makes developers richer, or makes players happier.  Some ideas that might be helpful: many developers want social media and screenshot sharing, player accounts, persisted player data, cross promotions etc.

Ben
